name: CI

on:
    pull_request_target: # For automated PRs (like changesets)
        branches:
            - main
        types:
            - opened
            - synchronize
            - reopened
            - ready_for_review
    pull_request: # For regular PRs from users
        branches:
            - main
        types:
            - opened
            - synchronize
            - reopened
            - ready_for_review

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: read

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.sha }} # Important for pull_request_target
                  fetch-depth: 0

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Lint
              run: bun lint:all

            - name: Build
              run: bun build:all
