name: PR

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint-and-build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Needed for Nx affected commands

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Lint
              run: bun lint:all

            - name: LS agent/src
              run: ls -a packages/agent/src

            - name: LS agent/src/Agent
              run: ls -a packages/agent/src/Agent

            - name: Build
              run: bun build:all
