name: Publish Packages

on:
    pull_request:
        types:
            - closed
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    publish-packages:
        if: github.event.pull_request.merged == true && github.event.pull_request.title == 'Version Packages'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: main
                  fetch-depth: 0
                  token: ${{ secrets.GH_TOKEN_CI }}

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Print .npmrc
              run: cat .npmrc

            - name: Install dependencies
              run: bun install

            - name: Lint
              run: bun lint:all

            - name: Build
              run: bun build:all

            - name: Publish Packages
              run: bun publish:all
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN_CI }}

            - name: Tag Release
              run: git tag v$(bun get-package-version) && git push origin --tags
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN_CI }}
