name: Version Packages

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    version-or-publish-packages:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: main
                  fetch-depth: 0
                  token: ${{ secrets.GH_TOKEN_CI }}

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Lint
              run: bun lint:all

            - name: Build
              run: bun build:all

            - name: Create Version Packages Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  title: 'Version Packages'
                  version: bun run version-packages
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN_CI }}

            - name: Publish Packages
              if: steps.changesets.outputs.hasChangesets == 'false'
              run: bun publish:all
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN_CI }}
