name: Version PR

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: main
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Create Version PR
              uses: changesets/action@v1
              with:
                  version: bun run version-packages
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
