name: Version Packages

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    version-packages:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: main
                  fetch-depth: 0
                  token: ${{ secrets.GH_TOKEN_CI }}

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Run CI (install, link, lint, test, build)
              run: bun ci

            - name: Create Version Packages Pull Request
              id: changesets
              uses: changesets/action@v1
              with:
                  title: 'Version Packages'
                  version: bun run version-packages
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN_CI }}
